spring:
   profiles:
      active:
      - dev
      
---
spring:
   profiles: dev
   application:
      name: provide
      
---
spring:
   profiles: test
   application:
      name: provide-test



